### ISSUE TITLE
Minimum width for columns

### ISSUE THREAD

**Issue by alexandre-mbm** [it4workflow/osmpoll#15]
![osmpoll-minumum-width](https://cloud.githubusercontent.com/assets/957501/7446656/2a3c76bc-f1b6-11e4-92b7-88c7629b497b.png)

**Comment by it4workflow** [comment]
the minimum i've already set with white-space: nowrap; in table-cell (date) and not in table-header, because i never know how long a translation could be.

**Comment by alexandre-mbm** [comment]
Why no also in table-header now that exists the case?
