### ISSUE TITLE
How to access the RSS feed translated?

### ISSUE THREAD

**Issue by alexandre-mbm** [it4workflow/osmpoll#3]
![osmpoll-feed-language](https://cloud.githubusercontent.com/assets/957501/7399676/c2a8391c-ee8d-11e4-97d0-108b4a87c51f.png)

**Comment by it4workflow** [comment]
http://osm.haraldhartmann.de/umfrage/rss now default in English and all open polls.
Append language isocode you get the localized feed, e.g. http://osm.haraldhartmann.de/umfrage/rss/pt - in future perhaps filtered to polls with this language isocode.
