### ISSUE TITLE
Bugs in portuguese version

### ISSUE THREAD

**Issue by alexandre-mbm** [it4workflow/osmpoll#5]
- [x] Without flag
  ![osmpoll-flag-bug1](https://cloud.githubusercontent.com/assets/957501/7407245/0c0ea8f4-eee6-11e4-85d8-845a2b4ebced.png)
- [x] Without flag and with wrong charset
  ![osmpoll-flag-bug2](https://cloud.githubusercontent.com/assets/957501/7407250/1325a21e-eee6-11e4-8310-ac8d098c4f00.png)
- [x] "Show N entries"
  ![osmpoll-shownentries](https://cloud.githubusercontent.com/assets/957501/7407290/9d42ce18-eee6-11e4-8fe0-81eae066d263.png)
- [x] "Search"
  ![osmpoll-search](https://cloud.githubusercontent.com/assets/957501/7407309/d4108110-eee6-11e4-8034-493b901d5d3e.png)
- [x] "Showing X to Y of Z entries"
  ![osmpoll-showxyzentries](https://cloud.githubusercontent.com/assets/957501/7407349/642dd4f0-eee7-11e4-9c97-a7e6c892fe63.png)
- [x] "Previous ... Next"
  ![osmpoll-previousnext](https://cloud.githubusercontent.com/assets/957501/7407374/c3948cae-eee7-11e4-96b6-7f50364aac0d.png)
- [ ] Dates
  ![osmpoll-dates](https://cloud.githubusercontent.com/assets/957501/7407417/17909b54-eee8-11e4-8926-e411a541db8b.png)
- [ ] Name
  ![osmpoll-name](https://cloud.githubusercontent.com/assets/957501/7407440/62e394da-eee8-11e4-999b-e0da823a9764.png)
- [x] "Hello!"
  ![osmpoll-hello](https://cloud.githubusercontent.com/assets/957501/7407462/bee6336e-eee8-11e4-9393-e3f6703a4f26.png)

**Comment by it4workflow** [comment]
- The dataTables feature is 3rd party feature i can't localize.
- Name will be changed to an english  term, such as QuestionBox or something else
- Greeting removed
- Dates changed to RFC2822

**Comment by alexandre-mbm** [comment]
Who is the 3rd part that makes the dataTables feature?

**Comment by it4workflow** [comment]
dataTables.net ... and now i found the internationalism and implemented it

**Comment by alexandre-mbm** [comment]
References:
- GitHub [DataTables/TableTools](https://github.com/DataTables/TableTools)
  - Internationalisation ‒ [datatables.net/manual/i18n](https://www.datatables.net/manual/i18n)
  - Internationalisation plug-ins ‒ [datatables.net/plug-ins/i18n/](https://www.datatables.net/plug-ins/i18n/)
