### ISSUE TITLE
Translate charts

### ISSUE THREAD

**Issue by alexandre-mbm** [it4workflow/osmpoll#6]
- [ ] Pizza  
  ![osmpoll-plot-pizza](https://cloud.githubusercontent.com/assets/957501/7407559/353df352-eeea-11e4-856f-3df230affa09.png)
- [ ] Bars  
  ![osmpoll-plot-bars](https://cloud.githubusercontent.com/assets/957501/7407627/caee7386-eeea-11e4-87c9-54d9079d4c04.png)
- [x] Time  
  ![osmpoll-plot-time](https://cloud.githubusercontent.com/assets/957501/7407675/2157fada-eeeb-11e4-8f69-06b80802eac2.png)

**Comment by alexandre-mbm** [comment]
I will need of the terms in English because Deutsh is very strange for me. Then I will do the 'pt'.

**Comment by it4workflow** [comment]
moved texts from stats.js to /app/language/(isocode)/stats.php, so you can translate pt/stats.php now

**Comment by alexandre-mbm** [comment]
I want to see as it is online please.

**Comment by alexandre-mbm** [comment]
Oops! Lacks this: "Nonrecurring" must be "Non recurring" that is "Não recorrente" in portuguese.

**Comment by it4workflow** [comment]
it's online.
the mapper types i won't translate cause i want to use the original "categories" from http://resultmaps.neis-one.org/oooc. and therefore i linked "status" to this page, just for explanation.

**Comment by alexandre-mbm** [comment]
Missing the term "Enthaltung". Would it be "abstentions"?

**Comment by it4workflow** [comment]
yes, "Enthaltung" is abstentions. the problem here is, that this is the database default value for answer with id=0. in the beginning it was n/a but german users can't do anything with it, so i changed it to "Enthaltun". i will slepp a night over this and hope i have a solution for this tomorrow

**Comment by alexandre-mbm** [comment]
@it4workflow, which your time zone or location?

**Comment by alexandre-mbm** [comment]
Do it put alias with i18n value for the result of SELECT? Note: I have not studied the code and I might not know what I am talking.
