### ISSUE TITLE
Error at screen /poll/create

### ISSUE THREAD

**Issue by alexandre-mbm** [it4workflow/osmpoll#9]
![osmpoll-error-at-create](https://cloud.githubusercontent.com/assets/957501/7431111/c2af9760-eff1-11e4-8b5c-4cc458db0c80.png)

**Comment by it4workflow** [comment]
fixed

**Comment by alexandre-mbm** [comment]
If you write like `fix #9` or `fixes #9` or `close #9` or `closes #9` in the commit message, it closes the issue. If you write like only `#9` or `ref. #9`, it references the commit at issue's page.

**Comment by it4workflow** [comment]
ok. thanks for this tip
